name: PyLint and MyPy

on: [push, pull_request]

jobs:
  lint:
    name: PyLint and MyPy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]
    steps:
      - name: Checkout Instaloader Repository
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install pipenv==2022.1.8
          pipenv sync --dev
      - name: PyLint
        run: pipenv run pylint instaloader
      - name: MyPy
        run: pipenv run mypy -m instaloader
